name: Price Monitor

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Call Monitor API
        run: |
          curl -X POST "https://bot-price-2.vercel.app/api/thala-monitor" \
            -H "Content-Type: application/json"
